# @BASE_URL = http://localhost:3000/

# GET {{BASE_URL}}

# ###
# GET {{BASE_URL}}12?sortBy=name

# ###
# POST {{BASE_URL}}
# Content-Type: application/json

# {
#     "name": "melo",
#     "age": 25
# }

# ###
# POST {{BASE_URL}}
# Content-Type: application/x-www-form-urlencoded

# name=melo&age=25

@BASE_URL = http://localhost:3000/api 

GET {{BASE_URL}}

###
GET {{BASE_URL}}/users 
###
GET {{BASE_URL}}/users/2 
###
POST {{BASE_URL}}/users
Content-Type: application/json

{
    "name": "melo",
    "email": "melosadsa",
    "userName": "medadsssa",
    "password": "123456"
}

###
PATCH  {{BASE_URL}}/users/6691808c392963f39faae275
Content-Type: application/json

{
    "userName": "meloss"
}
###
DELETE  {{BASE_URL}}/users/66917ac0f4b85fd05fb4a46b
Content-Type: application/json

